# Generated by Django 6.0.1 on 2026-01-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Format: YYYYMM (e.g. 202512)', max_length=6, unique=True)),
                ('year', models.IntegerField(editable=False)),
                ('month', models.IntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
