# Generated by Django 6.0.1 on 2026-01-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0002_remove_creator_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='achieved_milestones',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='creator',
            name='diamonds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='creator',
            name='estimated_bonus_contribution',
            field=models.FloatField(default=0.0),
        ),
    ]
