# Generated by Django 6.0.1 on 2026-01-20 10:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('creators', '0003_alter_creator_achieved_milestones_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='creator',
            unique_together={('user', 'report_month')},
        ),
    ]
