# Generated by Django 6.0.1 on 2026-02-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('creators', '0004_alter_creator_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='creator',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='creator',
            name='creator_uid',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='creator',
            unique_together={('creator_uid', 'report_month')},
        ),
    ]
