# Generated by Django 6.0.1 on 2026-01-18 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('eligible_creators', models.IntegerField(default=0)),
                ('estimated_bonus_contribution', models.CharField(blank=True, max_length=250)),
                ('diamonds', models.CharField(blank=True, max_length=250)),
                ('M_0_5', models.IntegerField(default=0)),
                ('M1', models.IntegerField(default=0)),
                ('M2', models.IntegerField(default=0)),
                ('M1R', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('report_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_managers', to='api.reportingmonth')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user',)},
            },
        ),
    ]
