# Generated by Django 6.0.1 on 2026-02-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0004_alter_manager_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='manager_uid',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
