# Generated by Django 6.0.1 on 2026-01-25 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('suggested_actions', models.JSONField(blank=True, default=list, null=True)),
                ('alert_type', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reportingmonth')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['report_month'], name='ai_insights_report__e9a99e_idx'), models.Index(fields=['priority'], name='ai_insights_priorit_679f53_idx')],
                'unique_together': {('user', 'report_month')},
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=150)),
                ('message', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at'], name='ai_insights_expires_268e9b_idx'), models.Index(fields=['user'], name='ai_insights_user_id_cc4f58_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reportingmonth')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['report_month', 'key'], name='ai_insights_report__a2541e_idx')],
                'unique_together': {('user', 'report_month', 'key')},
            },
        ),
        migrations.CreateModel(
            name='AIScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reportingmonth')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['report_month'], name='ai_insights_report__2d1f45_idx')],
                'unique_together': {('user', 'report_month')},
            },
        ),
        migrations.CreateModel(
            name='AITarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_milestone', models.CharField(blank=True, max_length=100, null=True)),
                ('target_diamonds', models.IntegerField(default=0)),
                ('reward_status', models.CharField(blank=True, max_length=100, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reportingmonth')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['report_month'], name='ai_insights_report__6a646e_idx')],
                'unique_together': {('user', 'report_month')},
            },
        ),
    ]
