# Generated by Django 6.0.1 on 2026-01-26 12:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_insights', '0002_aimanagertarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimanagertarget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
