# Generated by Django 6.0.1 on 2026-01-26 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_insights', '0003_aimanagertarget_created_at'),
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='aimetric',
            name='ai_insights_report__a2541e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='aimetric',
            unique_together={('user', 'report_month')},
        ),
        migrations.AddIndex(
            model_name='aimetric',
            index=models.Index(fields=['report_month'], name='ai_insights_report__1c5397_idx'),
        ),
        migrations.RemoveField(
            model_name='aimetric',
            name='key',
        ),
        migrations.RemoveField(
            model_name='aimetric',
            name='value',
        ),
    ]
