# Generated by Django 6.0.1 on 2026-01-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_insights', '0004_remove_aimetric_ai_insights_report__a2541e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimetric',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
