# Generated by Django 6.0.1 on 2026-01-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_insights', '0005_aimetric_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidailysummary',
            name='alert_message',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
