# Generated by Django 6.0.1 on 2026-02-07 23:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_insights', '0006_aidailysummary_alert_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimanagertarget',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 7, 23, 57, 6, 140445, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
