# Generated by Django 6.0 on 2026-02-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_insights', '0008_alter_aimessage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='aidailysummary',
            name='alert_message',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
